# Generated by Django 4.1.7 on 2023-03-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_func', models.IntegerField()),
                ('nome', models.CharField(max_length=80)),
                ('login', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=10)),
                ('adm', models.BooleanField()),
            ],
        ),
    ]
