# Generated by Django 4.1.7 on 2023-02-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='valor_promo',
            new_name='valor_prom',
        ),
    ]
