# Generated by Django 4.1.7 on 2023-02-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='cod_cliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='cod_produto',
            field=models.IntegerField(),
        ),
    ]
