# Generated by Django 4.1.7 on 2023-02-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_vendas_cod_cliente_alter_vendas_cod_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='alelo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='debito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='dinheiro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='end_entrega',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='gorjeta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='pix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='sodexo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='vr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
