# Generated by Django 4.1.7 on 2023-02-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vendas_estado_alter_vendas_alelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='alelo',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='cod_produto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='dinheiro',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='gorjeta',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='obs_prod',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='pix',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='qtd_prod',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='sodexo',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='valor_prod',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='vr',
        ),
        migrations.CreateModel(
            name='ProdutosVendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_prod', models.FloatField()),
                ('cod_produto', models.IntegerField()),
                ('desc_prod', models.CharField(max_length=50)),
                ('valor_prod', models.FloatField()),
                ('obs_prod', models.CharField(max_length=100)),
                ('dinheiro', models.FloatField(blank=True, null=True)),
                ('credito', models.FloatField(blank=True, null=True)),
                ('debito', models.FloatField(blank=True, null=True)),
                ('pix', models.FloatField(blank=True, null=True)),
                ('vr', models.FloatField(blank=True, null=True)),
                ('sodexo', models.FloatField(blank=True, null=True)),
                ('alelo', models.FloatField(blank=True, null=True)),
                ('gorjeta', models.FloatField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.vendas')),
            ],
        ),
    ]
