# Generated by Django 4.1.7 on 2023-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_vendas_alelo_remove_vendas_cod_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='cod_pedido',
        ),
        migrations.AddField(
            model_name='produtosvendidos',
            name='pedido',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produtosvendidos',
            name='obs_prod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
