# Generated by Django 4.1.7 on 2023-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_produtosvendidos_cod_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='estado',
        ),
        migrations.AddField(
            model_name='vendas',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
