# Generated by Django 4.1.7 on 2023-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_vendas_fone_cliente_vendas_nome_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosvendidos',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
