# Generated by Django 4.1.7 on 2023-04-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_produtosvendidos_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='alelo',
        ),
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='debito',
        ),
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='dinheiro',
        ),
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='gorjeta',
        ),
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='pix',
        ),
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='sodexo',
        ),
        migrations.RemoveField(
            model_name='produtosvendidos',
            name='vr',
        ),
        migrations.AddField(
            model_name='vendas',
            name='alelo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='credito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='debito',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='dinheiro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='gorjeta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='pix',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='sodexo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='vr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
