# Generated by Django 4.1.7 on 2023-04-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_produtosvendidos_alelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
