# Generated by Django 4.1.7 on 2023-05-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_vendas_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosvendidos',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
