# Generated by Django 4.1.7 on 2023-02-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='aniversario',
            new_name='aniver',
        ),
    ]
