# Generated by Django 4.1.7 on 2023-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_aniversario_clientes_aniver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='aniver',
            field=models.DateField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='comp',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='obs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
