# Generated by Django 4.1.7 on 2023-02-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_aniver_alter_clientes_comp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='aniver',
            field=models.DateField(null=True),
        ),
    ]
