# Generated by Django 4.1.7 on 2023-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoqueiros_Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motoqueiro', models.IntegerField()),
                ('pedido', models.IntegerField(null=True)),
                ('valor', models.FloatField(null=True)),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='motoqueiros',
            name='caixinha',
        ),
        migrations.RemoveField(
            model_name='motoqueiros',
            name='valor',
        ),
    ]
