# Generated by Django 4.1.7 on 2023-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0002_motoqueiros_entrega_remove_motoqueiros_caixinha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motoqueiros_entrega',
            name='estado',
            field=models.IntegerField(null=True),
        ),
    ]
