# Generated by Django 4.1.7 on 2023-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoqueiro', '0003_motoqueiros_entrega_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoqueiros_entrega',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
